---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payments-dev 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server:  https://kubernetes.default.svc
  project: default
  source:
      helm:
        parameters:
        - name: image.repository
          value: 683123961003.dkr.ecr.ap-south-1.amazonaws.com/payments
        - name: service.port
          value: '8080'
        - name: livenessProbe.httpGet.path
          value: /healthz
        - name: readinessProbe.httpGet.path
          value: /healthz
        - name: image.tag
          value: 0.1.0
      path: helm-charts/payments 
      repoURL: git@github.com:waqcas/k8s_argo_environments.git
      targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
