---
apiVersion: v1
kind: Secret
metadata:
  name: repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ssh://git@github.com/waqcas/k8s_argo_environments.git
  sshPrivateKey: |
     -----BEGIN OPENSSH PRIVATE KEY-----
     b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
     QyNTUxOQAAACD11u/TigXb1sGaqsA/atgSfKWEkazUoOnqdtEvLvsavwAAAJgTXBbCE1wW
     wgAAAAtzc2gtZWQyNTUxOQAAACD11u/TigXb1sGaqsA/atgSfKWEkazUoOnqdtEvLvsavw
     AAAEDK7H1NRoFRbzE7cnEhrtbCsWexI7ZJeru1NkOVDkot4vXW79OKBdvWwZqqwD9q2BJ8
     pYSRrNSg6ep20S8u+xq/AAAAEHdhcWNhc0BnbWFpbC5jb20BAgMEBQ==
     -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "false"
