---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: users-dev-imageupdater
  namespace: argocd
spec:
  commonUpdateSettings:
    updateStrategy: semver
    forceUpdate: false
  writeBackConfig:
    method: git
  applicationRefs:
  - namePattern: users-dev
    images:
    - alias: users
      imageName: 683123961003.dkr.ecr.ap-south-1.amazonaws.com/users:v0.1.x
      commonUpdateSettings:
        ignoreTags:
        - '*'
