helm:
  parameters:
  - name: image.name
    value: 683123961003.dkr.ecr.ap-south-1.amazonaws.com/payments
    forcestring: true
  - name: image.repository
    value: 683123961003.dkr.ecr.ap-south-1.amazonaws.com/payments
    forcestring: false
  - name: image.tag
    value: 0.1.6
    forcestring: true
  - name: livenessProbe.httpGet.path
    value: /healthz
    forcestring: false
  - name: readinessProbe.httpGet.path
    value: /healthz
    forcestring: false
  - name: service.port
    value: "8080"
    forcestring: false
